ok

diff --git a/bin/upgrade b/bin/upgrade
--- a/bin/upgrade
+++ b/bin/upgrade
@@ -2,63 +2,74 @@
 
 export HOMEBREW_NO_AUTO_UPDATE=0
 
+run () {
+  echo $(sudo -H -u oleander bash -c '$@')
+}
+
+set -e
 sudo ls
 
-echo "==> Upgrade 'm'"
-m --update
+echo "==> Stop indexing"
+index-stop
 
-echo "==> Set volume"
-m volume 0
+echo "Install updates"
+run m --update install all
 
-# echo "==> Lock computer"
-# m lock
-
-echo "==> Clean trash"
-m trash clean
-
-echo "==> Start indexing"
-index-start
-
-echo "==> Update brew"
-brew update
-
-echo "==> Upgrade brew"
-brew upgrade --fetch-HEAD --display-times
-
-echo "==> Repair brew"
-brew tap --repair
-
-echo "==> Clean up brew"
-brew cleanup --prune 7
-
-echo "==> Upgrade casks"
-brew cask fetch
-
-echo "==> Upgrade casks"
-brew cask upgrade
-
-echo "==> Upgrade NPM"
-npm install -g npm
-
-echo "==> Upgrade NPM"
-npm upgrade -g
-
-echo "==> Clear NPM cache"
-npm cache clean --force
-
-echo "==> Clear Yarn cache"
-yarn cache clean --force
-
-echo "==> Upgrade rubygems"
-gem install rubygems-update
-update_rubygems
-gem update --system
-
-echo "==> Clean up old gems"
-gem cleanup -y
-
-echo "==> Upgrade pip"
-pip-review --auto --local
-
-# echo "==> Verify disk"
-# m disk verify volume /Volumes/System
+# echo "==> Upgrade 'm'"
+# run m --update
+#
+# echo "==> Set volume"
+# run m volume 0
+#
+# echo "==> Upgrade APM packages"
+# run apm upgrade --no-confirm
+#
+# echo "==> Clean up APM"
+# run apm prune
+#
+# echo "==> Clean trash"
+# run m trash clean
+#
+# echo "==> Update brew index"
+# run brew update
+#
+# echo "==> Upgrade brew"
+# run brew upgrade --fetch-HEAD --display-times
+#
+# echo "==> Repair brew"
+# run brew tap --repair
+#
+# echo "==> Clean up brew"
+# run brew cleanup --prune 7
+#
+# echo "==> Upgrade cask brew"
+# run brew cask upgrade
+#
+# echo "==> Upgrade NPM"
+# run npm install -g npm
+#
+# # echo "==> Upgrade NPM"
+# # npm update -g
+#
+# echo "==> Clear NPM cache"
+# run npm cache clean --force
+#
+# echo "==> Upgrade rubygems"
+# run gem install rubygems-update
+# run update_rubygems
+# run gem update --system
+#
+# echo "==> Clean up old gems"
+# run gem cleanup
+#
+# echo "==> Upgrade pip"
+# run pip-review --auto --local
+#
+# #echo "==> Verify disk"
+# #m disk verify volume /Volumes/System
+#
+# #echo "==> Git GC all projects"
+# #find ~/Projekt -name '*.git' -execdir sh -c 'cd {} && git gc' \;
+#
+# echo "==> Start indexing"
+# index-start
